name: Java CI

on:
  push:
    branches: [mainline]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Get version
        if: github.event_name == 'push' && github.ref == 'refs/heads/mainline'
        id: get_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
      - name: Upload JAR artifact
        if: github.event_name == 'push' && github.ref == 'refs/heads/mainline'
        uses: actions/upload-artifact@v7
        with:
          name: CloudWatch-${{ steps.get_version.outputs.version }}
          path: target/CloudWatch-*.jar
          if-no-files-found: error
